blank_issues_enabled: false
contact_links:
  - name: Have a question? Need help? Want to chat?
    url: https://tbm-studios.com/discord
    about: Join our Discord server for community support, discussions, and the latest updates!
